## Average Word Vector
## Created by: Harsh Bari
## From: SVNIT, Gujarat
## Mtech Data Science - p23ds004 (2023-25)
## Subject: NLP Project
## Last Updated: 29/03/2024

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("final_dataset.csv")

In [3]:
data

tweets       class  \
0      Be aware  dirty step to get money  #staylight ...  figurative   
1      #sarcasm for #people who don't understand #diy...  figurative   
2      @IminworkJeremy @medsingle #DailyMail readers ...  figurative   
3      @wilw Why do I get the feeling you like games?...  figurative   
4      -@TeacherArthurG @rweingarten You probably jus...  figurative   
...                                                  ...         ...   
81403  Photo: Image via We Heart It http://t.co/ky8Nf...     sarcasm   
81404  I never knew..I better put this out to the Uni...     sarcasm   
81405  hey just wanted to say thanks @ puberty for le...     sarcasm   
81406  I'm sure coverage like the Fox News Special “T...     sarcasm   
81407  @skeyno16 at u13?! I won't believe it until I ...     sarcasm   

                                                  tokens  \
0      ['be', 'aware', 'dirty', 'step', 'to', 'get', ...   
1      ['sarcasm', 'for', 'people', 'who', 'don', 'un...   
2      ['iminworkjeremy', 'medsingle', 'dailymail', '...   
3      ['wilw', 'why', 'do', 'get', 'the', 'feeling',...   
4      ['teacherarthurg', 'rweingarten', 'you', 'prob...   
...                                                  ...   
81403  ['photo', 'image', 'via', 'we', 'heart', 'it',...   
81404  ['never', 'knew', 'better', 'put', 'this', 'ou...   
81405  ['hey', 'just', 'wanted', 'to', 'say', 'thanks...   
81406  ['sure', 'coverage', 'like', 'the', 'fox', 'ne...   
81407  ['skeyno', 'at', 'won', 'believe', 'it', 'unti...   

                                                word2vec  
0      [-1.19050758e-02  1.16620226e-01  1.97997382e-...  
1      [ 2.94221377e-02  2.08143203e-01  1.72751102e-...  
2      [-0.1235885   0.05067413  0.3733275  -0.227050...  
3      [-0.02185489  0.3480542   0.624338   -0.582425...  
4      [-0.05288212  0.1641525   0.54444376 -0.362433...  
...                                                  ...  
81403  [-1.84435886e-01  1.83419669e-01  3.13743446e-...  
81404  [ 0.01726132  0.19902723  0.38343058 -0.256441...  
81405  [-7.33005936e-05  1.17733040e-02  3.56954102e-...  
81406  [-0.08389465  0.100885    0.36214375 -0.300751...  
81407  [-0.02437943  0.19550255  0.49198555 -0.12781 ...  

[81408 rows x 4 columns]

In [4]:
data['word2vec']

0        [-1.19050758e-02  1.16620226e-01  1.97997382e-...
1        [ 2.94221377e-02  2.08143203e-01  1.72751102e-...
2        [-0.1235885   0.05067413  0.3733275  -0.227050...
3        [-0.02185489  0.3480542   0.624338   -0.582425...
4        [-0.05288212  0.1641525   0.54444376 -0.362433...
                               ...                        
81403    [-1.84435886e-01  1.83419669e-01  3.13743446e-...
81404    [ 0.01726132  0.19902723  0.38343058 -0.256441...
81405    [-7.33005936e-05  1.17733040e-02  3.56954102e-...
81406    [-0.08389465  0.100885    0.36214375 -0.300751...
81407    [-0.02437943  0.19550255  0.49198555 -0.12781 ...
Name: word2vec, Length: 81408, dtype: object

In [5]:
data['word2vec'][0]

'[-1.19050758e-02  1.16620226e-01  1.97997382e-01 -2.69489541e-01\n -7.66756877e-02  1.27769003e-01 -2.55769373e-01  9.86336611e-02\n  8.49334672e-02 -6.09500741e-02  1.84933924e-01  1.45254004e-01\n -1.05722736e-03  4.07291507e-02  4.14199961e-02 -1.04670005e-01\n  2.44177999e-01 -1.45667303e-01 -1.35545416e-01  2.11801241e-01\n  2.27879851e-01  1.34966927e-02  1.13493863e-02 -8.83673140e-02\n  3.29575739e-02  1.20378999e-01 -1.00660015e-02 -1.57044374e-01\n  8.74430709e-02 -1.54583151e-01 -2.78526134e-02  3.28145041e-01\n -2.69770028e-02  7.30823353e-03  2.09195139e-01  2.35272463e-01\n -8.58561351e-03 -3.60043399e-02  1.22844919e-01  2.76703938e-02\n -1.31999616e-01 -1.79826155e-01  4.65860034e-02 -3.88554156e-01\n -2.14142157e-01  1.52666937e-02 -1.65338843e-01 -1.78316311e-01\n  2.49726155e-02 -6.30770764e-01  4.04885411e-02 -6.33034941e-03\n  1.35558544e-01  6.40117851e-01 -1.91852385e-01 -1.19760076e+00\n  8.80471665e-02 -3.38173759e-02  7.96421535e-01 -2.04303846e-02\n -2.09942

In [6]:
data['class'].value_counts()

class
figurative    21238
irony         20894
sarcasm       20681
regular       18595
Name: count, dtype: int64

In [7]:
print(type(data['word2vec'][0]))

<class 'str'>


In [8]:
def str_to_vec(input_string):
    # Your input string
    # input_string = "[ 0.47350284 0.17998783 0.52607228 -0.21903914 0.50474907 -0.84181457\n 0.80536147 1.04832851 -0.31514828 -0.6643499 0.23167278 -0.84063938\n -0.42383317 0.31786839 0.38651903 0.43740021 0.19098905 0.03756036\n -0.37013237 -0.86544681 -0.60763254 -0.3359968 0.57907489 0.11688197\n 0.51970026 -0.2024598 -0.29698118 -0.15100316 0.13487357 -0.38675231\n 0.19580726 -0.21120347 -0.32096125 0.81528131 -0.12422152 -0.02690754\n -0.01132907 0.1541235 0.69146074 0.26843169 0.6963023 -0.79966018\n -0.21509953 -0.3805155 0.18800793 0.66235928 0.14572814 -0.41985339\n -0.28700945 -0.28272397 0.25726554 -0.37221263 0.02272534 -0.4292531\n -0.34494111 -0.10192458 -0.00632285 0.42416801 -0.18897754 -0.21455062\n -0.80645763 0.41921128 0.23389137 0.17909839 -0.37738952 0.55195239\n 0.03543126 -0.0540801 0.05538673 -0.29212652 -0.54393175 0.07931972\n -0.01140794 0.89003169 -0.164462 -0.37368158 0.09018268 -0.305098\n 0.14973728 0.44211518 -0.08145603 0.43468505 -0.74777054 0.15402889\n 0.61750253 -0.09117783 0.61714293 0.33495427 -0.02995716 0.0333282\n 0.71559205 -0.37184732 0.23758197 0.56563806 0.24524485 -0.22222566\n 0.57311822 -0.14456244 -0.71279361 -0.51761399]"

    # Remove brackets and newline characters
    cleaned_string = input_string.replace('[', '').replace(']', '').replace('\n', '')

    # Split the string into a list of strings
    string_values = cleaned_string.split()

    # Convert each string value to a float
    float_values = [float(value) for value in string_values]

    # Convert the list of floats to a NumPy array
    vector = np.array(float_values)

    # Now, 'vector' is a NumPy array representing your vector
    return vector

In [9]:
dataset = pd.DataFrame()

In [10]:
dataset['word2vec'] = data['word2vec'].apply(str_to_vec)

In [11]:
dataset

word2vec
0      [-0.0119050758, 0.116620226, 0.197997382, -0.2...
1      [0.0294221377, 0.208143203, 0.172751102, -0.41...
2      [-0.1235885, 0.05067413, 0.3733275, -0.2270506...
3      [-0.02185489, 0.3480542, 0.624338, -0.582425, ...
4      [-0.05288212, 0.1641525, 0.54444376, -0.362433...
...                                                  ...
81403  [-0.184435886, 0.183419669, 0.313743446, -0.29...
81404  [0.01726132, 0.19902723, 0.38343058, -0.256441...
81405  [-7.33005936e-05, 0.011773304, 0.356954102, -0...
81406  [-0.08389465, 0.100885, 0.36214375, -0.3007513...
81407  [-0.02437943, 0.19550255, 0.49198555, -0.12781...

[81408 rows x 1 columns]

In [12]:
print(len(data['word2vec']))

81408


In [13]:
dataset['word2vec'][0]

array([-1.19050758e-02,  1.16620226e-01,  1.97997382e-01, -2.69489541e-01,
       -7.66756877e-02,  1.27769003e-01, -2.55769373e-01,  9.86336611e-02,
        8.49334672e-02, -6.09500741e-02,  1.84933924e-01,  1.45254004e-01,
       -1.05722736e-03,  4.07291507e-02,  4.14199961e-02, -1.04670005e-01,
        2.44177999e-01, -1.45667303e-01, -1.35545416e-01,  2.11801241e-01,
        2.27879851e-01,  1.34966927e-02,  1.13493863e-02, -8.83673140e-02,
        3.29575739e-02,  1.20378999e-01, -1.00660015e-02, -1.57044374e-01,
        8.74430709e-02, -1.54583151e-01, -2.78526134e-02,  3.28145041e-01,
       -2.69770028e-02,  7.30823353e-03,  2.09195139e-01,  2.35272463e-01,
       -8.58561351e-03, -3.60043399e-02,  1.22844919e-01,  2.76703938e-02,
       -1.31999616e-01, -1.79826155e-01,  4.65860034e-02, -3.88554156e-01,
       -2.14142157e-01,  1.52666937e-02, -1.65338843e-01, -1.78316311e-01,
        2.49726155e-02, -6.30770764e-01,  4.04885411e-02, -6.33034941e-03,
        1.35558544e-01,  

### Create Input and Output

In [14]:
def create_input_vectors(vector):
    n = len(vector)
    array_2d = np.empty((n, len(vector[0])), dtype=object)

    # Create and insert 10 random 5D arrays into the 2D array
    for i in range(n):
        array_150d = vector[i]
        array_2d[i] = array_150d

    return array_2d


In [15]:
input_vec = create_input_vectors(dataset['word2vec'])

In [16]:
print(type(input_vec))

<class 'numpy.ndarray'>


In [17]:
print(input_vec.ndim)

2


In [18]:
mapping_dict = {'figurative': 0, 'irony': 1, 'sarcasm': 1, 'regular': 0}

# Use map to replace string values with numerical values
output = data['class'].map(mapping_dict).to_numpy()

In [19]:
print(output.ndim)

1


In [20]:
print(type(output))

<class 'numpy.ndarray'>


In [21]:
output

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

### Data Splitting

In [22]:
def split_data(array_2d, ranges_to_copy):
    copied_ranges = []

    # Loop through each range and copy the corresponding elements
    for start, end in ranges_to_copy:
        copied_range = array_2d[start:end+1]  # Adjust end index to include the last element
        copied_ranges.append(copied_range)

    # Concatenate the copied ranges along the first axis to create the final array
    copied_array = np.concatenate(copied_ranges, axis=0)

    return copied_array

In [23]:
x_train = split_data(input_vec, [(0, 16989), (21238, 37952), (42132, 57007), (60727, 77270)])
x_test = split_data(input_vec, [(16990, 21237), (37953, 42131), (57008, 60726), (77271, 81407)])

In [24]:
print("x train:", len(x_train))
print("x test:", len(x_test))
print("Total:", len(x_train) + len(x_test))

x train: 65125
x test: 16283
Total: 81408


In [25]:
y_train = np.concatenate((np.zeros(16990), np.ones(31591), np.zeros(16544)))
y_test = np.concatenate((np.zeros(4248), np.ones(7898), np.zeros(4137)))

In [26]:
print("train:", len(y_train))
print("test:", len(y_test))
print("total:", len(y_train) + len(y_test))

train: 65125
test: 16283
total: 81408


## Training With Neural Network

In [27]:
import tensorflow as tf
from tensorflow import keras

### Neural Network for Average Word Embedding

In [28]:
awe = keras.Sequential([
    keras.layers.Dense(256, input_shape = (150, ), activation = 'relu'),
    keras.layers.Dense(128, activation = 'relu'),
    keras.layers.Dense(64, activation = 'relu'),
    keras.layers.Dense(32, activation = 'relu'),
    keras.layers.Dense(16, activation=keras.layers.LeakyReLU(alpha=0.1)),
    keras.layers.Dense(8, activation=keras.layers.LeakyReLU(alpha=0.1)),
    keras.layers.Dense(2, activation = 'sigmoid')

])

awe.compile(optimizer = 'adam',
                      loss = 'sparse_categorical_crossentropy',
                      metrics = ['accuracy'])

### Check Model Summary

In [29]:
awe.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               38656     
                                                                 
 dense_1 (Dense)             (None, 128)               32896     
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 16)                528       
                                                                 
 dense_5 (Dense)             (None, 8)                 136       
                                                                 
 dense_6 (Dense)             (None, 2)                 1

### Train Model

In [30]:
awe.fit(x_train.astype(np.float32), y_train.astype(np.float32), epochs=22)

Epoch 1/22


2036/2036 [==============================] - 9s 3ms/step - loss: 0.4297 - accuracy: 0.7776
Epoch 2/22
2036/2036 [==============================] - 6s 3ms/step - loss: 0.3914 - accuracy: 0.7971
Epoch 3/22
2036/2036 [==============================] - 7s 3ms/step - loss: 0.3798 - accuracy: 0.8028
Epoch 4/22
2036/2036 [==============================] - 6s 3ms/step - loss: 0.3720 - accuracy: 0.8065
Epoch 5/22
2036/2036 [==============================] - 7s 3ms/step - loss: 0.3656 - accuracy: 0.8086
Epoch 6/22
2036/2036 [==============================] - 8s 4ms/step - loss: 0.3604 - accuracy: 0.8100
Epoch 7/22
2036/2036 [==============================] - 7s 4ms/step - loss: 0.3548 - accuracy: 0.8144
Epoch 8/22
2036/2036 [==============================] - 8s 4ms/step - loss: 0.3515 - accuracy: 0.8161
Epoch 9/22
2036/2036 [==============================] - 7s 4ms/step - loss: 0.3474 - accuracy: 0.8168
Epoch 10/22
2036/2036 [==============================] - 7s 4ms/step - loss: 0.3

### Training Accuracy

In [31]:
awe.evaluate(x_train.astype(np.float32), y_train.astype(np.float32))

2036/2036 [==============================] - 5s 2ms/step - loss: 0.3047 - accuracy: 0.8377


[0.30468904972076416, 0.837727427482605]

### Testing Accuracy

In [32]:
prediction = awe.predict(x_test.astype(np.float32))

509/509 [==============================] - 2s 2ms/step


In [33]:
prediction = np.argmax(prediction, axis = 1)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [35]:
print(classification_report(y_test.astype(np.float32), prediction))
print()
print("Confusion Matrix: \n", confusion_matrix(y_test.astype(np.float32), prediction))
print("\nAccuracy: \n", accuracy_score(y_test.astype(np.float32), prediction))

              precision    recall  f1-score   support

         0.0       0.90      0.76      0.83      8385
         1.0       0.78      0.91      0.84      7898

    accuracy                           0.84     16283
   macro avg       0.84      0.84      0.83     16283
weighted avg       0.84      0.84      0.83     16283


Confusion Matrix: 
 [[6407 1978]
 [ 703 7195]]

Accuracy: 
 0.8353497512743352
